# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

jobs:
  - job: build_on_windows
    pool:
      vmImage: 'windows-latest'

    variables:
      buildConfiguration: 'Release'

    steps:

    - task: GitVersion@4
      displayName: 'Generate a version number using GitVersion'
      inputs:
        updateAssemblyInfo: true

    - task: NuGetToolInstaller@1
      displayName: 'Use NuGet 4.4.1'
      inputs:
        versionSpec: 4.4.1
        checkLatest: true

    - task: MSBuild@1
      displayName: 'Build dotnet core application using MSBuild on Windows'
      inputs:
        msbuildLocationMethod: version
        msbuildVersion: latest
        msbuildArchitecture: x86
        msbuildArguments: /r /p:Configuration=$(buildConfiguration) /p:OutputPath=app /t:Publish /detailedsummary /m:16 /bl:$(build.artifactstagingdirectory)\build.binlog
        clean: false
        maximumCpuCount: true
        restoreNugetPackages: false
        logProjectEvents: false
        createLogFile: false

    - task: CopyFiles@2
      displayName: 'Copy compiled file into artifacts'
      inputs:
        SourceFolder: 'Zigbee2MqttAssistant/apppublish'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/app'

    - task: CmdLine@2
      displayName: 'Create a script file to restore version number on during release management'
      inputs:
        script: |
          echo ##vso[task.setvariable variable=GitVersion.SemVer]$(GitVersion.SemVer)>> "$(Build.ArtifactStagingDirectory)/restore-version.ps1"

    - task: PublishBuildArtifacts@1
      condition: always()
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Application'
        ArtifactType: Container

  - job: create_docker_on_linux
    dependsOn: build_on_windows
    pool:
      vmImage: 'ubuntu-latest'

    steps:

    - task: DownloadBuildArtifacts@0
      displayName: 'Restore artifacts compiled on Windows'
      inputs:
        downloadType: 'all'
        downloadPath: '$(Build.ArtifactStagingDirectory)'

    - task: DockerInstaller@0
      displayName: 'Install docker on CI agent'
      inputs:
        dockerVersion: '17.09.0-ce'

    - task: CopyFiles@2
      displayName: 'Copy artifacts to right folder for Docker build'
      inputs:
        SourceFolder: '$(Build.ArtifactStagingDirectory)/Application/app'
        Contents: '**'
        TargetFolder: 'Zigbee2MqttAssistant/apppublish'

    - task: CmdLine@2
      displayName: 'Build docker images'
      inputs:
        script: |
          docker build . -t zigbee2mqttassistant:$(Build.BuildId)
          docker save zigbee2mqttassistant:$(Build.BuildId) -o "$(Build.ArtifactStagingDirectory)/zigbee2mqttassistant-$(Build.BuildId).tar"

    - task: PublishBuildArtifacts@1
      displayName: 'Publish docker images as build artifacts'
      condition: always()
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Application'
        publishLocation: 'Container'
